tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "git"
brew "go"
brew "httpie"
brew "nvm"
brew "rustup"
brew "yarn"
brew "zsh"

cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "hyper"
cask "ngrok"
cask "notion"
cask "postman"
cask "skitch"
cask "slack"
cask "visual-studio-code"
cask "whatsapp"